### ISSUE TITLE
[BUG]Error while preparing WAN info: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by SeanChengN** [JuanManuelRomeroGarcia/hass-miwifi#10]
**Describe the bug**
此错误来自自定义集成。

日志记录器: miwifi
来源: custom_components/miwifi/updater.py:660
集成: MiWiFi (Xiaohack Edition) (文档, 问题)
首次出现: 12:46:12 (333 次总计出现)
上次记录: 13:17:34

Error while preparing WAN info: 'bool' object has no attribute 'get'

**Please complete the following information:**
 - HASS version: 2025.4.2
 - Component version 3.0.8
 - Router model AX3600 AX3000 AX6000
 - Router firmware version  1.1.25 (CN) 1.0.68 (CN) 1.0.122 (CN)

**Comment by JuanManuelRomeroGarcia** [comment]
Fixed, you can check

**Comment by SeanChengN** [comment]
Thanks for the quick fix, but the error still persists
![error_log.txt](https://github.com/user-attachments/files/19794300/error_log.txt)

**Comment by SeanChengN** [comment]
> 
> You are on version 3.0.8b2, I just resubmitted, please try again.
> 
> ![Image](https://github.com/user-attachments/assets/aabd8e84-b611-4e4c-89e0-f54539a7110e)
I tried the B2 version and now the error log is changed to:此错误来自自定义集成。

日志记录器: miwifi
来源: custom_components/miwifi/updater.py:664
集成: MiWiFi (Xiaohack Edition) (文档, 问题)
首次出现: 22:43:34 (6 次总计出现)
上次记录: 22:43:42

Error while preparing WAN info: WAN info['info'] is not a dictionary

**Comment by JuanManuelRomeroGarcia** [comment]
You can access /config/custom_components/miwifi/Log/config/custom_components/miwifi/updater.pys/miwifi_debug.log and send me the file and the file

**Comment by JuanManuelRomeroGarcia** [comment]
Please update again to v3.0.8b3 and if the error persists, please send me the log file located at /config/custom_components/miwifi/Logs/miwifi_debug.log

**Comment by SeanChengN** [comment]
B3 did not resolve the error

[miwifi_debug.log](https://github.com/user-attachments/files/19797403/miwifi_debug.log)

[updater.py.txt](https://github.com/user-attachments/files/19797413/updater.py.txt)

**Comment by JuanManuelRomeroGarcia** [comment]
Update to version 3.0.8b4, the error should no longer appear, since it was not an error, it was just a warning that I forgot to set it as debug, everything should now work ok without errors. You can confirm with the new version?

**Comment by SeanChengN** [comment]
> Update to version 3.0.8b4, the error should no longer appear, since it was not an error, it was just a warning that I forgot to set it as debug, everything should now work ok without errors. You can confirm with the new version?

It is now ok, and it is displayed in the Log Viewer with debug information.Could you add a switch to control debug information? It fills the Log Viewer.![Screenshot_2025-04-18-07-52-52-006_io.homeassistant.companion.android.jpg](https://github.com/user-attachments/assets/49982116-547a-491b-abbc-12b7ca964a20)

**Comment by JuanManuelRomeroGarcia** [comment]
Ok, I'm preparing the logs option for the next update.

**Comment by JuanManuelRomeroGarcia** [comment]
Ok, I'm preparing the logs option for the next update.
