### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by JuanManuelRomeroGarcia** [JuanManuelRomeroGarcia/hass-miwifi#12]
> Update to version 3.0.8b4, the error should no longer appear, since it was not an error, it was just a warning that I forgot to set it as debug, everything should now work ok without errors. You can confirm with the new version?
> 
> It is now ok, and it is displayed in the Log Viewer with debug information.Could you add a switch to control debug information? It fills the Log Viewer.![Screenshot_2025-04-18-07-52-52-006_io.homeassistant.companion.android.jpg](https://github.com/user-attachments/assets/49982116-547a-491b-abbc-12b7ca964a20)
> 
>  

 _Originally posted by @SeanChengN in [#10](https://github.com/JuanManuelRomeroGarcia/hass-miwifi/issues/10#issuecomment-2814217915)_

**Comment by JuanManuelRomeroGarcia** [comment]
FIXED

**Comment by Psytoshgen** [comment]
> FIXED
Not fixed, still spams debug messeges
![Image](https://github.com/user-attachments/assets/22b6c7a5-ef68-40e7-8d35-18cdf9a62a07)
